/****************************************************************************
**
** Namespace VmFrontendControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {0b169ebf-aec9-4983-9b52-ccf9bf8ce6cc}

****************************************************************************/

#ifndef QAX_DUMPCPP_VMFRONTENDCONTROLWINFORM_H
#define QAX_DUMPCPP_VMFRONTENDCONTROLWINFORM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VMFRONTENDCONTROLWINFORM_EXPORT
#define VMFRONTENDCONTROLWINFORM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace System {
    class ISite;
}

namespace mscorlib {
    class _Type;
    class _EventHandler;
}

Q_DECLARE_OPAQUE_POINTER(System::ISite*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_Type*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_EventHandler*)

namespace VmFrontendControlWinform {

// forward declarations
    struct LoadSolInfo;
    struct LoadSolInfo;

class VMFRONTENDCONTROLWINFORM_EXPORT VmFrontendInterface : public QAxObject
{
public:
    VmFrontendInterface(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /**
     * @par 说明
     * 自动缩放大小
	 * 需先LoadFrontendSource
     */
    inline void AutoChangeSize();

    /**
     * @brief 释放控件资源
	 * @remarks 控件销毁前调用一次
     */
    inline void Dispose();

    /**
     * @par 说明
     * 初始化
     */
    inline qlonglong GetObjectPointer();

    /**
     * @par 说明
     * 加载运行界面
	 * 需先LoadSol
     */
    inline void LoadFrontendSource();

    /**
     * @par 说明
     * 加载方案
	 * @param pSol [in] 方案信息结构体地址 结构详见VmControlBaseInfo.h的SolutionInputInfo
     */
    inline void LoadSol(qlonglong pSol);
	
	/**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
    */
    inline void SetParamTabEditable(bool isEditable);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VMFRONTENDCONTROLWINFORM_EXPORT VmFrontendControlWinform : public QAxWidget
{
public:
    VmFrontendControlWinform(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{32db9666-8d63-471a-add9-1a7013d8dec6}"));
    }

//    VmFrontendControlWinform(IComponent *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmFrontendControlWinform(IDisposable *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmFrontendControlWinform(IWin32Window *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

    VmFrontendControlWinform(VmFrontendInterface *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Site
    */
    inline System::ISite* Site() const; //Returns the value of Site
    inline void SetSite(System::ISite* value); //Sets the value of the Site property

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /**
     * @par 说明
     * 自动缩放大小
	 * 需先LoadFrontendSource
     */
    inline void AutoChangeSize();

    /*
    Method Dispose
    */
    inline void Dispose();

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /**
     * @par 说明
     * 初始化
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /**
     * @par 说明
     * 加载运行界面
	 * 需先LoadSol
     */
    inline void LoadFrontendSource();

    /**
     * @par 说明
     * 加载方案
	 * @param pSol [in] 方案信息结构体地址 结构详见VmControlBaseInfo.h的SolutionInputInfo
     */
    inline void LoadSol(qlonglong pSol);

	/**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method add_Disposed
    */
    inline void add_Disposed(mscorlib::_EventHandler* value);

    /*
    Method remove_Disposed
    */
    inline void remove_Disposed(mscorlib::_EventHandler* value);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VMFRONTENDCONTROLWINFORM_NOINLINES
inline int VmFrontendControlWinform::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline System::ISite* VmFrontendControlWinform::Site() const
{
#ifdef QAX_DUMPCPP_SYSTEM_H
    System::ISite* qax_pointer = 0;
    qRegisterMetaType<System::ISite*>("System::ISite*", &qax_pointer);
    qRegisterMetaType<System::ISite>("System::ISite", qax_pointer);
    QVariant qax_result = property("Site");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(System::ISite**)qax_result.constData();
#else
    return 0; // foreign namespace not included
#endif
}
inline void VmFrontendControlWinform::SetSite(System::ISite* value){
    int typeId = qRegisterMetaType<System::ISite*>("System::ISite*", &value);
    setProperty("Site", QVariant(typeId, &value));
}

inline QString VmFrontendControlWinform::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline void VmFrontendControlWinform::AutoChangeSize()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline void VmFrontendControlWinform::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
}

inline bool VmFrontendControlWinform::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline int VmFrontendControlWinform::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline qlonglong VmFrontendControlWinform::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline mscorlib::_Type* VmFrontendControlWinform::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline void VmFrontendControlWinform::LoadFrontendSource()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
}

inline void VmFrontendControlWinform::LoadSol(qlonglong pSol)
{
    void *_a[] = {0, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void VmFrontendControlWinform::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VmFrontendControlWinform::add_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void VmFrontendControlWinform::remove_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}


inline void VmFrontendInterface::AutoChangeSize()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void VmFrontendInterface::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline qlonglong VmFrontendInterface::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline void VmFrontendInterface::LoadFrontendSource()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
}

inline void VmFrontendInterface::LoadSol(qlonglong pSol)
{
    void *_a[] = {0, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void VmFrontendInterface::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VmFrontendControlWinform::VmFrontendControlWinform, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmFrontendControlWinform::VmFrontendControlWinform*>(t)->VmFrontendControlWinform::~VmFrontendControlWinform();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmFrontendControlWinform::VmFrontendControlWinform;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmFrontendControlWinform::VmFrontendControlWinform*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmFrontendControlWinform::VmFrontendControlWinform*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VmFrontendControlWinform::VmFrontendInterface, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmFrontendControlWinform::VmFrontendInterface*>(t)->VmFrontendControlWinform::VmFrontendInterface::~VmFrontendInterface();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmFrontendControlWinform::VmFrontendInterface;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmFrontendControlWinform::VmFrontendInterface*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmFrontendControlWinform::VmFrontendInterface*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

