/****************************************************************************
**
** Metadata for VmFrontendControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {0b169ebf-aec9-4983-9b52-ccf9bf8ce6cc}

****************************************************************************/

#define QAX_DUMPCPP_VMFRONTENDCONTROLWINFORM_NOINLINES
#include "vmfrontendcontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[44];
    char stringdata0[536];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 50, 0),
QT_MOC_LITERAL(1, 51, 11, 0),
QT_MOC_LITERAL(2, 63, 10, 0),
QT_MOC_LITERAL(3, 74, 11, 0),
QT_MOC_LITERAL(4, 86, 11, 0),
QT_MOC_LITERAL(5, 98, 11, 0),
QT_MOC_LITERAL(6, 110, 12, 0),
QT_MOC_LITERAL(7, 123, 11, 0),
QT_MOC_LITERAL(8, 135, 19, 0),
QT_MOC_LITERAL(9, 155, 9, 0),
QT_MOC_LITERAL(10, 165, 0, 0),
QT_MOC_LITERAL(11, 166, 4, 0),
QT_MOC_LITERAL(12, 171, 6, 0),
QT_MOC_LITERAL(13, 178, 4, 0),
QT_MOC_LITERAL(14, 183, 4, 0),
QT_MOC_LITERAL(15, 188, 15, 0),
QT_MOC_LITERAL(16, 204, 4, 0),
QT_MOC_LITERAL(17, 209, 6, 0),
QT_MOC_LITERAL(18, 216, 4, 0),
QT_MOC_LITERAL(19, 221, 4, 0),
QT_MOC_LITERAL(20, 226, 14, 0),
QT_MOC_LITERAL(21, 241, 7, 0),
QT_MOC_LITERAL(22, 249, 6, 0),
QT_MOC_LITERAL(23, 256, 3, 0),
QT_MOC_LITERAL(24, 260, 11, 0),
QT_MOC_LITERAL(25, 272, 16, 0),
QT_MOC_LITERAL(26, 289, 7, 0),
QT_MOC_LITERAL(27, 297, 16, 0),
QT_MOC_LITERAL(28, 314, 6, 0),
QT_MOC_LITERAL(29, 321, 18, 0),
QT_MOC_LITERAL(30, 340, 7, 0),
QT_MOC_LITERAL(31, 348, 4, 0),
QT_MOC_LITERAL(32, 353, 19, 0),
QT_MOC_LITERAL(33, 373, 10, 0),
QT_MOC_LITERAL(34, 384, 7, 0),
QT_MOC_LITERAL(35, 392, 14, 0),
QT_MOC_LITERAL(36, 407, 4, 0),
QT_MOC_LITERAL(37, 412, 12, 0),
QT_MOC_LITERAL(38, 425, 24, 0),
QT_MOC_LITERAL(39, 450, 5, 0),
QT_MOC_LITERAL(40, 456, 15, 0),
QT_MOC_LITERAL(41, 472, 8, 0),
QT_MOC_LITERAL(42, 481, 45, 0),
QT_MOC_LITERAL(43, 527, 7, 0)
    },
    "VmFrontendControlWinform::VmFrontendControlWinform\0Interface 1\0IComponent\0"
    "Interface 2\0IDisposable\0Interface 3\0IWin32Window\0Interface 4\0VmFrontendInterface\0"
    "exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0"
    "AutoChangeSize\0Dispose\0Equals\0obj\0GetHashCode\0GetObjectPointer\0GetType\0"
    "mscorlib::_Type*\0Handle\0LoadFrontendSource\0LoadSol\0pSol\0SetParamTabEditable\0"
    "isEditable\0SetSite\0System::ISite*\0Site\0add_Disposed\0mscorlib::_EventHandler*\0"
    "value\0remove_Disposed\0ToString\0VmFrontendControlWinform::VmFrontendInterface\0"
    "control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmFrontendControlWinform__VmFrontendControlWinform[] = {

 // content:
    7, // revision
    0,  // classname
    4, 14, // classinfo
    16, 22, // methods
    3, 146, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 
    5, 6, 
    7, 8, 

// signal: name, argc, parameters, tag, flags
    9, 4, 102, 10, 5,
    15, 1, 111, 10, 5,
    17, 3, 114, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 0, 121, 10, 9,
    21, 0, 122, 10, 9,
    22, 1, 123, 10, 9,
    24, 0, 126, 10, 9,
    25, 0, 127, 10, 9,
    26, 0, 128, 10, 9,
    28, 0, 129, 10, 9,
    29, 0, 130, 10, 9,
    30, 1, 131, 10, 9,
    32, 1, 134, 10, 9,
    34, 1, 137, 10, 9,
    37, 1, 140, 10, 9,
    40, 1, 143, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 23,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 27,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::LongLong, 31,
    QMetaType::Void, QMetaType::Bool, 33,
    QMetaType::Void, 0x80000000 | 35, 36,
    QMetaType::Void, 0x80000000 | 38, 39,
    QMetaType::Void, 0x80000000 | 38, 39,

 // properties: name, type, flags
    28, QMetaType::Int, 0x02005001, 		 // int Handle
    36, 0x80000000 | 35, 0x00015003, 		 // System::ISite* Site
    41, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmFrontendControlWinform::VmFrontendControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmFrontendControlWinform__VmFrontendControlWinform, 0, 0, 0 }
};

void *VmFrontendControlWinform::VmFrontendControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmFrontendControlWinform::VmFrontendControlWinform"))
        return static_cast<void*>(const_cast<VmFrontendControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_VmFrontendControlWinform__VmFrontendInterface[] = {

 // content:
    7, // revision
    42,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 88, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    9, 4, 59, 10, 5,
    15, 1, 68, 10, 5,
    17, 3, 71, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 0, 78, 10, 9,
    21, 0, 79, 10, 9,
    25, 0, 80, 10, 9,
    29, 0, 81, 10, 9,
    30, 1, 82, 10, 9,
    32, 1, 85, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::Void,
    QMetaType::Void, QMetaType::LongLong, 31,
    QMetaType::Void, QMetaType::Bool, 33,

 // properties: name, type, flags
    43, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmFrontendControlWinform::VmFrontendInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmFrontendControlWinform__VmFrontendInterface, 0, 0, 0 }
};

void *VmFrontendControlWinform::VmFrontendInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmFrontendControlWinform::VmFrontendInterface"))
        return static_cast<void*>(const_cast<VmFrontendInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}

