/****************************************************************************
**
** Metadata for VmGlobalToolWinform generated by dumpcpp v5.9.9 using
** dumpcpp {f04fb571-b351-484b-b8a1-2259803cb499}

****************************************************************************/

#define QAX_DUMPCPP_VMGLOBALTOOLWINFORM_NOINLINES
#include "vmglobaltoolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[38];
    char stringdata0[447];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 42, 0),
QT_MOC_LITERAL(1, 43, 9, 0),
QT_MOC_LITERAL(2, 53, 0, 0),
QT_MOC_LITERAL(3, 54, 4, 0),
QT_MOC_LITERAL(4, 59, 6, 0),
QT_MOC_LITERAL(5, 66, 4, 0),
QT_MOC_LITERAL(6, 71, 4, 0),
QT_MOC_LITERAL(7, 76, 15, 0),
QT_MOC_LITERAL(8, 92, 4, 0),
QT_MOC_LITERAL(9, 97, 6, 0),
QT_MOC_LITERAL(10, 104, 4, 0),
QT_MOC_LITERAL(11, 109, 4, 0),
QT_MOC_LITERAL(12, 114, 7, 0),
QT_MOC_LITERAL(13, 122, 16, 0),
QT_MOC_LITERAL(14, 139, 7, 0),
QT_MOC_LITERAL(15, 147, 40, 0),
QT_MOC_LITERAL(16, 188, 11, 0),
QT_MOC_LITERAL(17, 200, 10, 0),
QT_MOC_LITERAL(18, 211, 11, 0),
QT_MOC_LITERAL(19, 223, 11, 0),
QT_MOC_LITERAL(20, 235, 11, 0),
QT_MOC_LITERAL(21, 247, 12, 0),
QT_MOC_LITERAL(22, 260, 11, 0),
QT_MOC_LITERAL(23, 272, 21, 0),
QT_MOC_LITERAL(24, 294, 6, 0),
QT_MOC_LITERAL(25, 301, 3, 0),
QT_MOC_LITERAL(26, 305, 11, 0),
QT_MOC_LITERAL(27, 317, 7, 0),
QT_MOC_LITERAL(28, 325, 16, 0),
QT_MOC_LITERAL(29, 342, 6, 0),
QT_MOC_LITERAL(30, 349, 7, 0),
QT_MOC_LITERAL(31, 357, 14, 0),
QT_MOC_LITERAL(32, 372, 4, 0),
QT_MOC_LITERAL(33, 377, 12, 0),
QT_MOC_LITERAL(34, 390, 24, 0),
QT_MOC_LITERAL(35, 415, 5, 0),
QT_MOC_LITERAL(36, 421, 15, 0),
QT_MOC_LITERAL(37, 437, 8, 0)
    },
    "VmGlobalToolWinform::VmGlobalToolInterface\0exception\0\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0Dispose\0GetObjectPointer\0control\0"
    "VmGlobalToolWinform::VmGlobalToolWinform\0Interface 1\0IComponent\0Interface 2\0"
    "IDisposable\0Interface 3\0IWin32Window\0Interface 4\0VmGlobalToolInterface\0Equals\0"
    "obj\0GetHashCode\0GetType\0mscorlib::_Type*\0Handle\0SetSite\0System::ISite*\0Site\0"
    "add_Disposed\0mscorlib::_EventHandler*\0value\0remove_Disposed\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmGlobalToolWinform__VmGlobalToolInterface[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    5, 14, // methods
    1, 60, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 39, 2, 5,
    7, 1, 48, 2, 5,
    9, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 58, 2, 9,
    13, 0, 59, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::LongLong,

 // properties: name, type, flags
    14, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmGlobalToolWinform::VmGlobalToolInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmGlobalToolWinform__VmGlobalToolInterface, 0, 0, 0 }
};

void *VmGlobalToolWinform::VmGlobalToolInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmGlobalToolWinform::VmGlobalToolInterface"))
        return static_cast<void*>(const_cast<VmGlobalToolInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VmGlobalToolWinform__VmGlobalToolWinform[] = {

 // content:
    7, // revision
    15,  // classname
    4, 14, // classinfo
    12, 22, // methods
    3, 118, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    16, 17, 
    18, 19, 
    20, 21, 
    22, 23, 

// signal: name, argc, parameters, tag, flags
    1, 4, 82, 2, 5,
    7, 1, 91, 2, 5,
    9, 3, 94, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 101, 2, 9,
    24, 1, 102, 2, 9,
    26, 0, 105, 2, 9,
    13, 0, 106, 2, 9,
    27, 0, 107, 2, 9,
    29, 0, 108, 2, 9,
    30, 1, 109, 2, 9,
    33, 1, 112, 2, 9,
    36, 1, 115, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 25,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 28,
    QMetaType::Int,
    QMetaType::Void, 0x80000000 | 31, 32,
    QMetaType::Void, 0x80000000 | 34, 35,
    QMetaType::Void, 0x80000000 | 34, 35,

 // properties: name, type, flags
    29, QMetaType::Int, 0x02005001, 		 // int Handle
    32, 0x80000000 | 31, 0x00015003, 		 // System::ISite* Site
    37, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmGlobalToolWinform::VmGlobalToolWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmGlobalToolWinform__VmGlobalToolWinform, 0, 0, 0 }
};

void *VmGlobalToolWinform::VmGlobalToolWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmGlobalToolWinform::VmGlobalToolWinform"))
        return static_cast<void*>(const_cast<VmGlobalToolWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}

