/****************************************************************************
**
** Namespace VmMainViewControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {a99a068f-b94f-4414-86a4-e0e472e95dfb}

****************************************************************************/

#ifndef QAX_DUMPCPP_VMMAINVIEWCONTROLWINFORM_H
#define QAX_DUMPCPP_VMMAINVIEWCONTROLWINFORM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VMMAINVIEWCONTROLWINFORM_EXPORT
#define VMMAINVIEWCONTROLWINFORM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace System {
    class ISite;
}

namespace mscorlib {
    class _Type;
    class _EventHandler;
}

Q_DECLARE_OPAQUE_POINTER(System::ISite*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_Type*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_EventHandler*)

namespace VmMainViewControlWinform {


class VMMAINVIEWCONTROLWINFORM_EXPORT VmMainViewControlInterface : public QAxObject
{
public:
    VmMainViewControlInterface(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /**
     * @par 说明
     * 绑定多流程
     */
    inline void BindMultiProcedure();

    /**
     * @par 说明
     * 绑定单流程
	 * @param name [in] 流程名称
	 * 绑定单流程后不支持加载方案，导入流程
     */	
    inline void BindSingleProcedure(const QString& name);

    /**
     * @brief 释放控件资源
	 * @remarks 控件销毁前调用一次
     */
    inline void Dispose();

    /**
     * @par 说明
     * 初始化（加载方案前调用）
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /**
     * @par 说明
     * 锁定工作区
     */
    inline void LockWorkArea();

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method UnlockWorkArea
    */
    inline void UnlockWorkArea();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VMMAINVIEWCONTROLWINFORM_EXPORT VmMainViewControlWinform : public QAxWidget
{
public:
    VmMainViewControlWinform(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{650ffbdc-5e28-4314-8901-7f02e6145414}"));
    }

//    VmMainViewControlWinform(IComponent *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmMainViewControlWinform(IDisposable *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmMainViewControlWinform(IWin32Window *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

    VmMainViewControlWinform(VmMainViewControlInterface *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Site
    */
    inline System::ISite* Site() const; //Returns the value of Site
    inline void SetSite(System::ISite* value); //Sets the value of the Site property

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /**
     * @par 说明
     * 绑定多流程
     */
    inline void BindMultiProcedure();

    /**
     * @par 说明
     * 绑定单流程
	 * @param name [in] 流程名称
	 * 绑定单流程后不支持加载方案，导入流程
     */	
    inline void BindSingleProcedure(const QString& name);

    /*
    Method Dispose
    */
    inline void Dispose();

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /**
     * @par 说明
     * 初始化（加载方案前调用）
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /**
     * @par 说明
     * 锁定工作区
     */
    inline void LockWorkArea();

    /**
     * @par 说明
     * 解锁工作区
     */
    inline void UnlockWorkArea();

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method add_Disposed
    */
    inline void add_Disposed(mscorlib::_EventHandler* value);

    /*
    Method remove_Disposed
    */
    inline void remove_Disposed(mscorlib::_EventHandler* value);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VMMAINVIEWCONTROLWINFORM_NOINLINES
inline void VmMainViewControlInterface::BindMultiProcedure()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void VmMainViewControlInterface::BindSingleProcedure(const QString& name)
{
    void *_a[] = {0, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void VmMainViewControlInterface::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline qlonglong VmMainViewControlInterface::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void VmMainViewControlInterface::LockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void VmMainViewControlInterface::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void VmMainViewControlInterface::UnlockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}


inline int VmMainViewControlWinform::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline System::ISite* VmMainViewControlWinform::Site() const
{
#ifdef QAX_DUMPCPP_SYSTEM_H
    System::ISite* qax_pointer = 0;
    qRegisterMetaType<System::ISite*>("System::ISite*", &qax_pointer);
    qRegisterMetaType<System::ISite>("System::ISite", qax_pointer);
    QVariant qax_result = property("Site");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(System::ISite**)qax_result.constData();
#else
    return 0; // foreign namespace not included
#endif
}
inline void VmMainViewControlWinform::SetSite(System::ISite* value){
    int typeId = qRegisterMetaType<System::ISite*>("System::ISite*", &value);
    setProperty("Site", QVariant(typeId, &value));
}

inline QString VmMainViewControlWinform::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline void VmMainViewControlWinform::BindMultiProcedure()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline void VmMainViewControlWinform::BindSingleProcedure(const QString& name)
{
    void *_a[] = {0, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
}

inline void VmMainViewControlWinform::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
}

inline bool VmMainViewControlWinform::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline int VmMainViewControlWinform::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline qlonglong VmMainViewControlWinform::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline mscorlib::_Type* VmMainViewControlWinform::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline void VmMainViewControlWinform::LockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void VmMainViewControlWinform::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VmMainViewControlWinform::UnlockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void VmMainViewControlWinform::add_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}

inline void VmMainViewControlWinform::remove_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VmMainViewControlWinform::VmMainViewControlInterface, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmMainViewControlWinform::VmMainViewControlInterface*>(t)->VmMainViewControlWinform::VmMainViewControlInterface::~VmMainViewControlInterface();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmMainViewControlWinform::VmMainViewControlInterface;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmMainViewControlWinform::VmMainViewControlInterface*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmMainViewControlWinform::VmMainViewControlInterface*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VmMainViewControlWinform::VmMainViewControlWinform, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmMainViewControlWinform::VmMainViewControlWinform*>(t)->VmMainViewControlWinform::~VmMainViewControlWinform();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmMainViewControlWinform::VmMainViewControlWinform;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmMainViewControlWinform::VmMainViewControlWinform*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmMainViewControlWinform::VmMainViewControlWinform*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

