/****************************************************************************
**
** Metadata for VmParamsControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {65a112e9-f3dd-4dcf-bf8b-dcf64958213f}

****************************************************************************/

#define QAX_DUMPCPP_VMPARAMSCONTROLWINFORM_NOINLINES
#include "vmparamscontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[45];
    char stringdata0[533];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 46, 0),
QT_MOC_LITERAL(1, 47, 11, 0),
QT_MOC_LITERAL(2, 59, 10, 0),
QT_MOC_LITERAL(3, 70, 11, 0),
QT_MOC_LITERAL(4, 82, 11, 0),
QT_MOC_LITERAL(5, 94, 11, 0),
QT_MOC_LITERAL(6, 106, 12, 0),
QT_MOC_LITERAL(7, 119, 11, 0),
QT_MOC_LITERAL(8, 131, 17, 0),
QT_MOC_LITERAL(9, 149, 9, 0),
QT_MOC_LITERAL(10, 159, 0, 0),
QT_MOC_LITERAL(11, 160, 4, 0),
QT_MOC_LITERAL(12, 165, 6, 0),
QT_MOC_LITERAL(13, 172, 4, 0),
QT_MOC_LITERAL(14, 177, 4, 0),
QT_MOC_LITERAL(15, 182, 15, 0),
QT_MOC_LITERAL(16, 198, 4, 0),
QT_MOC_LITERAL(17, 203, 6, 0),
QT_MOC_LITERAL(18, 210, 4, 0),
QT_MOC_LITERAL(19, 215, 4, 0),
QT_MOC_LITERAL(20, 220, 7, 0),
QT_MOC_LITERAL(21, 228, 6, 0),
QT_MOC_LITERAL(22, 235, 3, 0),
QT_MOC_LITERAL(23, 239, 11, 0),
QT_MOC_LITERAL(24, 251, 16, 0),
QT_MOC_LITERAL(25, 268, 7, 0),
QT_MOC_LITERAL(26, 276, 16, 0),
QT_MOC_LITERAL(27, 293, 6, 0),
QT_MOC_LITERAL(28, 300, 20, 0),
QT_MOC_LITERAL(29, 321, 4, 0),
QT_MOC_LITERAL(30, 326, 7, 0),
QT_MOC_LITERAL(31, 334, 19, 0),
QT_MOC_LITERAL(32, 354, 10, 0),
QT_MOC_LITERAL(33, 365, 13, 0),
QT_MOC_LITERAL(34, 379, 5, 0),
QT_MOC_LITERAL(35, 385, 7, 0),
QT_MOC_LITERAL(36, 393, 14, 0),
QT_MOC_LITERAL(37, 408, 4, 0),
QT_MOC_LITERAL(38, 413, 12, 0),
QT_MOC_LITERAL(39, 426, 24, 0),
QT_MOC_LITERAL(40, 451, 5, 0),
QT_MOC_LITERAL(41, 457, 15, 0),
QT_MOC_LITERAL(42, 473, 8, 0),
QT_MOC_LITERAL(43, 482, 41, 0),
QT_MOC_LITERAL(44, 524, 7, 0)
    },
    "VmParamsControlWinform::VmParamsControlWinform\0Interface 1\0IComponent\0"
    "Interface 2\0IDisposable\0Interface 3\0IWin32Window\0Interface 4\0VmParamsInterface\0"
    "exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0Dispose\0"
    "Equals\0obj\0GetHashCode\0GetObjectPointer\0GetType\0mscorlib::_Type*\0Handle\0"
    "LoadIndependentGroup\0pSol\0LoadSol\0SetParamTabEditable\0isEditable\0SetParamsInfo\0"
    "pData\0SetSite\0System::ISite*\0Site\0add_Disposed\0mscorlib::_EventHandler*\0value\0"
    "remove_Disposed\0ToString\0VmParamsControlWinform::VmParamsInterface\0control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmParamsControlWinform__VmParamsControlWinform[] = {

 // content:
    7, // revision
    0,  // classname
    4, 14, // classinfo
    16, 22, // methods
    3, 150, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 
    5, 6, 
    7, 8, 

// signal: name, argc, parameters, tag, flags
    9, 4, 102, 10, 5,
    15, 1, 111, 10, 5,
    17, 3, 114, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 0, 121, 10, 9,
    21, 1, 122, 10, 9,
    23, 0, 125, 10, 9,
    24, 0, 126, 10, 9,
    25, 0, 127, 10, 9,
    27, 0, 128, 10, 9,
    28, 1, 129, 10, 9,
    30, 1, 132, 10, 9,
    31, 1, 135, 10, 9,
    33, 1, 138, 10, 9,
    35, 1, 141, 10, 9,
    38, 1, 144, 10, 9,
    41, 1, 147, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 22,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 26,
    QMetaType::Int,
    QMetaType::LongLong, QMetaType::LongLong, 29,
    QMetaType::LongLong, QMetaType::LongLong, 29,
    QMetaType::Void, QMetaType::Bool, 32,
    QMetaType::Void, QMetaType::LongLong, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, 0x80000000 | 39, 40,

 // properties: name, type, flags
    27, QMetaType::Int, 0x02005001, 		 // int Handle
    37, 0x80000000 | 36, 0x00015003, 		 // System::ISite* Site
    42, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmParamsControlWinform::VmParamsControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmParamsControlWinform__VmParamsControlWinform, 0, 0, 0 }
};

void *VmParamsControlWinform::VmParamsControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmParamsControlWinform::VmParamsControlWinform"))
        return static_cast<void*>(const_cast<VmParamsControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_VmParamsControlWinform__VmParamsInterface[] = {

 // content:
    7, // revision
    43,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 92, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    9, 4, 59, 10, 5,
    15, 1, 68, 10, 5,
    17, 3, 71, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 0, 78, 10, 9,
    24, 0, 79, 10, 9,
    28, 1, 80, 10, 9,
    30, 1, 83, 10, 9,
    31, 1, 86, 10, 9,
    33, 1, 89, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::LongLong, QMetaType::LongLong, 29,
    QMetaType::LongLong, QMetaType::LongLong, 29,
    QMetaType::Void, QMetaType::Bool, 32,
    QMetaType::Void, QMetaType::LongLong, 34,

 // properties: name, type, flags
    44, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmParamsControlWinform::VmParamsInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmParamsControlWinform__VmParamsInterface, 0, 0, 0 }
};

void *VmParamsControlWinform::VmParamsInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmParamsControlWinform::VmParamsInterface"))
        return static_cast<void*>(const_cast<VmParamsInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}

