/****************************************************************************
**
** Metadata for VmRealTimeAcqControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {FED63791-1D4F-4F7A-89AA-A8F34F951AD8}

****************************************************************************/

#define QAX_DUMPCPP_VMREALTIMEACQCONTROLWINFORM_NOINLINES
#include "vmrealtimeacqcontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[44];
    char stringdata0[551];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 58, 0),
QT_MOC_LITERAL(1, 59, 9, 0),
QT_MOC_LITERAL(2, 69, 0, 0),
QT_MOC_LITERAL(3, 70, 4, 0),
QT_MOC_LITERAL(4, 75, 6, 0),
QT_MOC_LITERAL(5, 82, 4, 0),
QT_MOC_LITERAL(6, 87, 4, 0),
QT_MOC_LITERAL(7, 92, 15, 0),
QT_MOC_LITERAL(8, 108, 4, 0),
QT_MOC_LITERAL(9, 113, 6, 0),
QT_MOC_LITERAL(10, 120, 4, 0),
QT_MOC_LITERAL(11, 125, 4, 0),
QT_MOC_LITERAL(12, 130, 7, 0),
QT_MOC_LITERAL(13, 138, 16, 0),
QT_MOC_LITERAL(14, 155, 13, 0),
QT_MOC_LITERAL(15, 169, 5, 0),
QT_MOC_LITERAL(16, 175, 10, 0),
QT_MOC_LITERAL(17, 186, 5, 0),
QT_MOC_LITERAL(18, 192, 13, 0),
QT_MOC_LITERAL(19, 206, 12, 0),
QT_MOC_LITERAL(20, 219, 7, 0),
QT_MOC_LITERAL(21, 227, 56, 0),
QT_MOC_LITERAL(22, 284, 11, 0),
QT_MOC_LITERAL(23, 296, 10, 0),
QT_MOC_LITERAL(24, 307, 11, 0),
QT_MOC_LITERAL(25, 319, 11, 0),
QT_MOC_LITERAL(26, 331, 11, 0),
QT_MOC_LITERAL(27, 343, 12, 0),
QT_MOC_LITERAL(28, 356, 11, 0),
QT_MOC_LITERAL(29, 368, 29, 0),
QT_MOC_LITERAL(30, 398, 6, 0),
QT_MOC_LITERAL(31, 405, 3, 0),
QT_MOC_LITERAL(32, 409, 11, 0),
QT_MOC_LITERAL(33, 421, 7, 0),
QT_MOC_LITERAL(34, 429, 16, 0),
QT_MOC_LITERAL(35, 446, 6, 0),
QT_MOC_LITERAL(36, 453, 7, 0),
QT_MOC_LITERAL(37, 461, 14, 0),
QT_MOC_LITERAL(38, 476, 4, 0),
QT_MOC_LITERAL(39, 481, 12, 0),
QT_MOC_LITERAL(40, 494, 24, 0),
QT_MOC_LITERAL(41, 519, 5, 0),
QT_MOC_LITERAL(42, 525, 15, 0),
QT_MOC_LITERAL(43, 541, 8, 0)
    },
    "VmRealTimeAcqControlWinform::VmRealTimeAcqControlInterface\0exception\0\0code\0"
    "source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0Dispose\0GetObjectPointer\0"
    "SetParamsInfo\0pData\0ShowButton\0bFlag\0StartGrabbing\0StopGrabbing\0control\0"
    "VmRealTimeAcqControlWinform::VmRealTimeAcqControlWinform\0Interface 1\0IComponent\0"
    "Interface 2\0IDisposable\0Interface 3\0IWin32Window\0Interface 4\0"
    "VmRealTimeAcqControlInterface\0Equals\0obj\0GetHashCode\0GetType\0mscorlib::_Type*\0"
    "Handle\0SetSite\0System::ISite*\0Site\0add_Disposed\0mscorlib::_EventHandler*\0"
    "value\0remove_Disposed\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmRealTimeAcqControlWinform__VmRealTimeAcqControlInterface[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    9, 14, // methods
    1, 88, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 59, 2, 5,
    7, 1, 68, 2, 5,
    9, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 78, 2, 9,
    13, 0, 79, 2, 9,
    14, 1, 80, 2, 9,
    16, 1, 83, 2, 9,
    18, 0, 86, 2, 9,
    19, 0, 87, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::Void, QMetaType::LongLong, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    20, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmRealTimeAcqControlWinform::VmRealTimeAcqControlInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmRealTimeAcqControlWinform__VmRealTimeAcqControlInterface, 0, 0, 0 }
};

void *VmRealTimeAcqControlWinform::VmRealTimeAcqControlInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmRealTimeAcqControlWinform::VmRealTimeAcqControlInterface"))
        return static_cast<void*>(const_cast<VmRealTimeAcqControlInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VmRealTimeAcqControlWinform__VmRealTimeAcqControlWinform[] = {

 // content:
    7, // revision
    21,  // classname
    4, 14, // classinfo
    16, 22, // methods
    3, 146, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    22, 23, 
    24, 25, 
    26, 27, 
    28, 29, 

// signal: name, argc, parameters, tag, flags
    1, 4, 102, 2, 5,
    7, 1, 111, 2, 5,
    9, 3, 114, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 121, 2, 9,
    30, 1, 122, 2, 9,
    32, 0, 125, 2, 9,
    13, 0, 126, 2, 9,
    33, 0, 127, 2, 9,
    35, 0, 128, 2, 9,
    14, 1, 129, 2, 9,
    36, 1, 132, 2, 9,
    16, 1, 135, 2, 9,
    18, 0, 138, 2, 9,
    19, 0, 139, 2, 9,
    39, 1, 140, 2, 9,
    42, 1, 143, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 31,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 34,
    QMetaType::Int,
    QMetaType::Void, QMetaType::LongLong, 15,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 40, 41,
    QMetaType::Void, 0x80000000 | 40, 41,

 // properties: name, type, flags
    35, QMetaType::Int, 0x02005001, 		 // int Handle
    38, 0x80000000 | 37, 0x00015003, 		 // System::ISite* Site
    43, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmRealTimeAcqControlWinform::VmRealTimeAcqControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmRealTimeAcqControlWinform__VmRealTimeAcqControlWinform, 0, 0, 0 }
};

void *VmRealTimeAcqControlWinform::VmRealTimeAcqControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmRealTimeAcqControlWinform::VmRealTimeAcqControlWinform"))
        return static_cast<void*>(const_cast<VmRealTimeAcqControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}

