/****************************************************************************
**
** Metadata for VmRenderControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {c3987c98-720a-414d-86d0-0d46ce541623}

****************************************************************************/

#define QAX_DUMPCPP_VMRENDERCONTROLWINFORM_NOINLINES
#include "vmrendercontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[79];
    char stringdata0[996];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 46, 0),
QT_MOC_LITERAL(1, 47, 11, 0),
QT_MOC_LITERAL(2, 59, 10, 0),
QT_MOC_LITERAL(3, 70, 11, 0),
QT_MOC_LITERAL(4, 82, 11, 0),
QT_MOC_LITERAL(5, 94, 11, 0),
QT_MOC_LITERAL(6, 106, 12, 0),
QT_MOC_LITERAL(7, 119, 11, 0),
QT_MOC_LITERAL(8, 131, 21, 0),
QT_MOC_LITERAL(9, 153, 9, 0),
QT_MOC_LITERAL(10, 163, 0, 0),
QT_MOC_LITERAL(11, 164, 4, 0),
QT_MOC_LITERAL(12, 169, 6, 0),
QT_MOC_LITERAL(13, 176, 4, 0),
QT_MOC_LITERAL(14, 181, 4, 0),
QT_MOC_LITERAL(15, 186, 15, 0),
QT_MOC_LITERAL(16, 202, 4, 0),
QT_MOC_LITERAL(17, 207, 6, 0),
QT_MOC_LITERAL(18, 214, 4, 0),
QT_MOC_LITERAL(19, 219, 4, 0),
QT_MOC_LITERAL(20, 224, 29, 0),
QT_MOC_LITERAL(21, 254, 22, 0),
QT_MOC_LITERAL(22, 277, 16, 0),
QT_MOC_LITERAL(23, 294, 7, 0),
QT_MOC_LITERAL(24, 302, 11, 0),
QT_MOC_LITERAL(25, 314, 6, 0),
QT_MOC_LITERAL(26, 321, 3, 0),
QT_MOC_LITERAL(27, 325, 11, 0),
QT_MOC_LITERAL(28, 337, 16, 0),
QT_MOC_LITERAL(29, 354, 27, 0),
QT_MOC_LITERAL(30, 382, 7, 0),
QT_MOC_LITERAL(31, 390, 16, 0),
QT_MOC_LITERAL(32, 407, 6, 0),
QT_MOC_LITERAL(33, 414, 18, 0),
QT_MOC_LITERAL(34, 433, 8, 0),
QT_MOC_LITERAL(35, 442, 17, 0),
QT_MOC_LITERAL(36, 460, 8, 0),
QT_MOC_LITERAL(37, 469, 10, 0),
QT_MOC_LITERAL(38, 480, 17, 0),
QT_MOC_LITERAL(39, 498, 16, 0),
QT_MOC_LITERAL(40, 515, 14, 0),
QT_MOC_LITERAL(41, 530, 10, 0),
QT_MOC_LITERAL(42, 541, 13, 0),
QT_MOC_LITERAL(43, 555, 5, 0),
QT_MOC_LITERAL(44, 561, 9, 0),
QT_MOC_LITERAL(45, 571, 7, 0),
QT_MOC_LITERAL(46, 579, 10, 0),
QT_MOC_LITERAL(47, 590, 8, 0),
QT_MOC_LITERAL(48, 599, 18, 0),
QT_MOC_LITERAL(49, 618, 8, 0),
QT_MOC_LITERAL(50, 627, 7, 0),
QT_MOC_LITERAL(51, 635, 5, 0),
QT_MOC_LITERAL(52, 641, 13, 0),
QT_MOC_LITERAL(53, 655, 5, 0),
QT_MOC_LITERAL(54, 661, 11, 0),
QT_MOC_LITERAL(55, 673, 9, 0),
QT_MOC_LITERAL(56, 683, 10, 0),
QT_MOC_LITERAL(57, 694, 8, 0),
QT_MOC_LITERAL(58, 703, 11, 0),
QT_MOC_LITERAL(59, 715, 9, 0),
QT_MOC_LITERAL(60, 725, 12, 0),
QT_MOC_LITERAL(61, 738, 10, 0),
QT_MOC_LITERAL(62, 749, 18, 0),
QT_MOC_LITERAL(63, 768, 6, 0),
QT_MOC_LITERAL(64, 775, 17, 0),
QT_MOC_LITERAL(65, 793, 12, 0),
QT_MOC_LITERAL(66, 806, 7, 0),
QT_MOC_LITERAL(67, 814, 14, 0),
QT_MOC_LITERAL(68, 829, 4, 0),
QT_MOC_LITERAL(69, 834, 7, 0),
QT_MOC_LITERAL(70, 842, 5, 0),
QT_MOC_LITERAL(71, 848, 18, 0),
QT_MOC_LITERAL(72, 867, 10, 0),
QT_MOC_LITERAL(73, 878, 12, 0),
QT_MOC_LITERAL(74, 891, 24, 0),
QT_MOC_LITERAL(75, 916, 15, 0),
QT_MOC_LITERAL(76, 932, 8, 0),
QT_MOC_LITERAL(77, 941, 45, 0),
QT_MOC_LITERAL(78, 987, 7, 0)
    },
    "VmRenderControlWinform::VmRenderControlWinform\0Interface 1\0IComponent\0"
    "Interface 2\0IDisposable\0Interface 3\0IWin32Window\0Interface 4\0VmRenderCtrlInterface\0"
    "exception\0\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0"
    "ChangeImageComboBoxVisibility\0isImageComboBoxVisible\0ClearDisplayView\0Dispose\0"
    "EnlargeView\0Equals\0obj\0GetHashCode\0GetObjectPointer\0GetSelectedImageDisplayName\0"
    "GetType\0mscorlib::_Type*\0Handle\0HideCoordinateInfo\0InitView\0SaveOriginalImage\0"
    "fileName\0jpgQuality\0SaveRenderedImage\0SetAnnularSector\0pAnnularSector\0"
    "isAddShape\0SetBackground\0value\0SetCircle\0pCircle\0SetEllipse\0pEllipse\0"
    "SetImageSourceData\0pImgData\0SetLine\0pLine\0SetParamsInfo\0pData\0SetPointSet\0"
    "pPointSet\0SetPolygon\0pPolygon\0SetPolyline\0pPolyline\0SetRectangle\0pRectangle\0"
    "SetRenderCondition\0status\0SetRenderInterval\0pMillseconds\0SetSite\0System::ISite*\0"
    "Site\0SetText\0pText\0ShowCoordinateInfo\0ShrinkView\0add_Disposed\0mscorlib::_EventHandler*\0"
    "remove_Disposed\0ToString\0VmRenderControlWinform::VmRenderCtrlInterface\0control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmRenderControlWinform__VmRenderControlWinform[] = {

 // content:
    7, // revision
    0,  // classname
    4, 14, // classinfo
    47, 22, // methods
    3, 406, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 
    5, 6, 
    7, 8, 

// signal: name, argc, parameters, tag, flags
    9, 4, 257, 10, 5,
    15, 1, 266, 10, 5,
    17, 3, 269, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 276, 10, 9,
    22, 0, 279, 10, 9,
    23, 0, 280, 10, 9,
    24, 0, 281, 10, 9,
    25, 1, 282, 10, 9,
    27, 0, 285, 10, 9,
    28, 0, 286, 10, 9,
    29, 0, 287, 10, 9,
    30, 0, 288, 10, 9,
    32, 0, 289, 10, 9,
    33, 0, 290, 10, 9,
    34, 0, 291, 10, 9,
    35, 1, 292, 10, 11,
    35, 2, 295, 10, 9,
    38, 1, 300, 10, 11,
    38, 2, 303, 10, 9,
    39, 1, 308, 10, 11,
    39, 2, 311, 10, 9,
    42, 1, 316, 10, 9,
    44, 1, 319, 10, 11,
    44, 2, 322, 10, 9,
    46, 1, 327, 10, 11,
    46, 2, 330, 10, 9,
    48, 1, 335, 10, 9,
    50, 1, 338, 10, 11,
    50, 2, 341, 10, 9,
    52, 1, 346, 10, 9,
    54, 1, 349, 10, 11,
    54, 2, 352, 10, 9,
    56, 1, 357, 10, 11,
    56, 2, 360, 10, 9,
    58, 1, 365, 10, 11,
    58, 2, 368, 10, 9,
    60, 1, 373, 10, 11,
    60, 2, 376, 10, 9,
    62, 1, 381, 10, 9,
    64, 1, 384, 10, 9,
    66, 1, 387, 10, 9,
    69, 1, 390, 10, 11,
    69, 2, 393, 10, 9,
    71, 0, 398, 10, 9,
    72, 0, 399, 10, 9,
    73, 1, 400, 10, 9,
    75, 1, 403, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 21,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 26,
    QMetaType::Int,
    QMetaType::LongLong,
    QMetaType::QString,
    0x80000000 | 31,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 36, 37,
    QMetaType::Void, QMetaType::QString, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 36, 37,
    QMetaType::Void, QMetaType::LongLong, 40,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 40, 41,
    QMetaType::Void, QMetaType::QString, 43,
    QMetaType::Void, QMetaType::LongLong, 45,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 45, 41,
    QMetaType::Void, QMetaType::LongLong, 47,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 47, 41,
    QMetaType::Void, QMetaType::LongLong, 49,
    QMetaType::Void, QMetaType::LongLong, 51,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 51, 41,
    QMetaType::Void, QMetaType::LongLong, 53,
    QMetaType::Void, QMetaType::LongLong, 55,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 55, 41,
    QMetaType::Void, QMetaType::LongLong, 57,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 57, 41,
    QMetaType::Void, QMetaType::LongLong, 59,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 59, 41,
    QMetaType::Void, QMetaType::LongLong, 61,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 61, 41,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, 0x80000000 | 67, 68,
    QMetaType::Void, QMetaType::LongLong, 70,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 70, 41,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 74, 43,
    QMetaType::Void, 0x80000000 | 74, 43,

 // properties: name, type, flags
    32, QMetaType::Int, 0x02005001, 		 // int Handle
    68, 0x80000000 | 67, 0x00015003, 		 // System::ISite* Site
    76, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmRenderControlWinform::VmRenderControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmRenderControlWinform__VmRenderControlWinform, 0, 0, 0 }
};

void *VmRenderControlWinform::VmRenderControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmRenderControlWinform::VmRenderControlWinform"))
        return static_cast<void*>(const_cast<VmRenderControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_VmRenderControlWinform__VmRenderCtrlInterface[] = {

 // content:
    7, // revision
    77,  // classname
    0, 0, // classinfo
    40, 14, // methods
    1, 348, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    9, 4, 214, 10, 5,
    15, 1, 223, 10, 5,
    17, 3, 226, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 233, 10, 9,
    22, 0, 236, 10, 9,
    23, 0, 237, 10, 9,
    24, 0, 238, 10, 9,
    28, 0, 239, 10, 9,
    29, 0, 240, 10, 9,
    33, 0, 241, 10, 9,
    34, 0, 242, 10, 9,
    35, 1, 243, 10, 11,
    35, 2, 246, 10, 9,
    38, 1, 251, 10, 11,
    38, 2, 254, 10, 9,
    39, 1, 259, 10, 11,
    39, 2, 262, 10, 9,
    42, 1, 267, 10, 9,
    44, 1, 270, 10, 11,
    44, 2, 273, 10, 9,
    46, 1, 278, 10, 11,
    46, 2, 281, 10, 9,
    48, 1, 286, 10, 9,
    50, 1, 289, 10, 11,
    50, 2, 292, 10, 9,
    52, 1, 297, 10, 9,
    54, 1, 300, 10, 11,
    54, 2, 303, 10, 9,
    56, 1, 308, 10, 11,
    56, 2, 311, 10, 9,
    58, 1, 316, 10, 11,
    58, 2, 319, 10, 9,
    60, 1, 324, 10, 11,
    60, 2, 327, 10, 9,
    62, 1, 332, 10, 9,
    64, 1, 335, 10, 9,
    69, 1, 338, 10, 11,
    69, 2, 341, 10, 9,
    71, 0, 346, 10, 9,
    72, 0, 347, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 21,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::QString,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 36, 37,
    QMetaType::Void, QMetaType::QString, 36,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 36, 37,
    QMetaType::Void, QMetaType::LongLong, 40,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 40, 41,
    QMetaType::Void, QMetaType::QString, 43,
    QMetaType::Void, QMetaType::LongLong, 45,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 45, 41,
    QMetaType::Void, QMetaType::LongLong, 47,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 47, 41,
    QMetaType::Void, QMetaType::LongLong, 49,
    QMetaType::Void, QMetaType::LongLong, 51,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 51, 41,
    QMetaType::Void, QMetaType::LongLong, 53,
    QMetaType::Void, QMetaType::LongLong, 55,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 55, 41,
    QMetaType::Void, QMetaType::LongLong, 57,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 57, 41,
    QMetaType::Void, QMetaType::LongLong, 59,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 59, 41,
    QMetaType::Void, QMetaType::LongLong, 61,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 61, 41,
    QMetaType::Void, QMetaType::Int, 63,
    QMetaType::Void, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::LongLong, 70,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 70, 41,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    78, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmRenderControlWinform::VmRenderCtrlInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmRenderControlWinform__VmRenderCtrlInterface, 0, 0, 0 }
};

void *VmRenderControlWinform::VmRenderCtrlInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmRenderControlWinform::VmRenderCtrlInterface"))
        return static_cast<void*>(const_cast<VmRenderCtrlInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}

