/****************************************************************************
**
** Metadata for VmMainViewControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {a99a068f-b94f-4414-86a4-e0e472e95dfb}

****************************************************************************/

#define QAX_DUMPCPP_VMMAINVIEWCONTROLWINFORM_NOINLINES
#include "vmmainviewcontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[44];
    char stringdata0[570];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 52, 0),
QT_MOC_LITERAL(1, 53, 9, 0),
QT_MOC_LITERAL(2, 63, 0, 0),
QT_MOC_LITERAL(3, 64, 4, 0),
QT_MOC_LITERAL(4, 69, 6, 0),
QT_MOC_LITERAL(5, 76, 4, 0),
QT_MOC_LITERAL(6, 81, 4, 0),
QT_MOC_LITERAL(7, 86, 15, 0),
QT_MOC_LITERAL(8, 102, 4, 0),
QT_MOC_LITERAL(9, 107, 6, 0),
QT_MOC_LITERAL(10, 114, 4, 0),
QT_MOC_LITERAL(11, 119, 4, 0),
QT_MOC_LITERAL(12, 124, 18, 0),
QT_MOC_LITERAL(13, 143, 19, 0),
QT_MOC_LITERAL(14, 163, 7, 0),
QT_MOC_LITERAL(15, 171, 16, 0),
QT_MOC_LITERAL(16, 188, 12, 0),
QT_MOC_LITERAL(17, 201, 19, 0),
QT_MOC_LITERAL(18, 221, 10, 0),
QT_MOC_LITERAL(19, 232, 14, 0),
QT_MOC_LITERAL(20, 247, 7, 0),
QT_MOC_LITERAL(21, 255, 50, 0),
QT_MOC_LITERAL(22, 306, 11, 0),
QT_MOC_LITERAL(23, 318, 10, 0),
QT_MOC_LITERAL(24, 329, 11, 0),
QT_MOC_LITERAL(25, 341, 11, 0),
QT_MOC_LITERAL(26, 353, 11, 0),
QT_MOC_LITERAL(27, 365, 12, 0),
QT_MOC_LITERAL(28, 378, 11, 0),
QT_MOC_LITERAL(29, 390, 26, 0),
QT_MOC_LITERAL(30, 417, 6, 0),
QT_MOC_LITERAL(31, 424, 3, 0),
QT_MOC_LITERAL(32, 428, 11, 0),
QT_MOC_LITERAL(33, 440, 7, 0),
QT_MOC_LITERAL(34, 448, 16, 0),
QT_MOC_LITERAL(35, 465, 6, 0),
QT_MOC_LITERAL(36, 472, 7, 0),
QT_MOC_LITERAL(37, 480, 14, 0),
QT_MOC_LITERAL(38, 495, 4, 0),
QT_MOC_LITERAL(39, 500, 12, 0),
QT_MOC_LITERAL(40, 513, 24, 0),
QT_MOC_LITERAL(41, 538, 5, 0),
QT_MOC_LITERAL(42, 544, 15, 0),
QT_MOC_LITERAL(43, 560, 8, 0)
    },
    "VmMainViewControlWinform::VmMainViewControlInterface\0exception\0\0code\0source\0"
    "disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0BindMultiProcedure\0"
    "BindSingleProcedure\0Dispose\0GetObjectPointer\0LockWorkArea\0SetParamTabEditable\0"
    "isEditable\0UnlockWorkArea\0control\0VmMainViewControlWinform::VmMainViewControlWinform\0"
    "Interface 1\0IComponent\0Interface 2\0IDisposable\0Interface 3\0IWin32Window\0"
    "Interface 4\0VmMainViewControlInterface\0Equals\0obj\0GetHashCode\0GetType\0"
    "mscorlib::_Type*\0Handle\0SetSite\0System::ISite*\0Site\0add_Disposed\0"
    "mscorlib::_EventHandler*\0value\0remove_Disposed\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmMainViewControlWinform__VmMainViewControlInterface[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    10, 14, // methods
    1, 94, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 64, 2, 5,
    7, 1, 73, 2, 5,
    9, 3, 76, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 83, 2, 9,
    13, 1, 84, 2, 9,
    14, 0, 87, 2, 9,
    15, 0, 88, 2, 9,
    16, 0, 89, 2, 9,
    17, 1, 90, 2, 9,
    19, 0, 93, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 18,
    QMetaType::Void,

 // properties: name, type, flags
    20, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmMainViewControlWinform::VmMainViewControlInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmMainViewControlWinform__VmMainViewControlInterface, 0, 0, 0 }
};

void *VmMainViewControlWinform::VmMainViewControlInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmMainViewControlWinform::VmMainViewControlInterface"))
        return static_cast<void*>(const_cast<VmMainViewControlInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VmMainViewControlWinform__VmMainViewControlWinform[] = {

 // content:
    7, // revision
    21,  // classname
    4, 14, // classinfo
    17, 22, // methods
    3, 152, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    22, 23, 
    24, 25, 
    26, 27, 
    28, 29, 

// signal: name, argc, parameters, tag, flags
    1, 4, 107, 2, 5,
    7, 1, 116, 2, 5,
    9, 3, 119, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 126, 2, 9,
    13, 1, 127, 2, 9,
    14, 0, 130, 2, 9,
    30, 1, 131, 2, 9,
    32, 0, 134, 2, 9,
    15, 0, 135, 2, 9,
    33, 0, 136, 2, 9,
    35, 0, 137, 2, 9,
    16, 0, 138, 2, 9,
    17, 1, 139, 2, 9,
    36, 1, 142, 2, 9,
    19, 0, 145, 2, 9,
    39, 1, 146, 2, 9,
    42, 1, 149, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 31,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 34,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 18,
    QMetaType::Void, 0x80000000 | 37, 38,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 40, 41,
    QMetaType::Void, 0x80000000 | 40, 41,

 // properties: name, type, flags
    35, QMetaType::Int, 0x02005001, 		 // int Handle
    38, 0x80000000 | 37, 0x00015003, 		 // System::ISite* Site
    43, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmMainViewControlWinform::VmMainViewControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmMainViewControlWinform__VmMainViewControlWinform, 0, 0, 0 }
};

void *VmMainViewControlWinform::VmMainViewControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmMainViewControlWinform::VmMainViewControlWinform"))
        return static_cast<void*>(const_cast<VmMainViewControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}

