/****************************************************************************
**
** Namespace VmParamsControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {65a112e9-f3dd-4dcf-bf8b-dcf64958213f}

****************************************************************************/

#ifndef QAX_DUMPCPP_VMPARAMSCONTROLWINFORM_H
#define QAX_DUMPCPP_VMPARAMSCONTROLWINFORM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VMPARAMSCONTROLWINFORM_EXPORT
#define VMPARAMSCONTROLWINFORM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace System {
    class ISite;
}

namespace mscorlib {
    class _Type;
    class _EventHandler;
}

Q_DECLARE_OPAQUE_POINTER(System::ISite*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_Type*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_EventHandler*)

namespace VmParamsControlWinform {

// forward declarations
    struct ParamBaseIn;
    struct LoadGroInfo;
    struct LoadSolInfo;
    struct ParamBaseIn;
    struct LoadGroInfo;
    struct LoadSolInfo;

class VMPARAMSCONTROLWINFORM_EXPORT VmParamsInterface : public QAxObject
{
public:
    VmParamsInterface(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /**
     * @brief 释放控件资源
	 * @remarks 控件销毁前调用一次
     */
    inline void Dispose();

    /**
     * @par 说明
     * 初始化
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /**
     * @par 说明
     * 导入独立Group
	 * @param pSol [in] Group信息结构体地址 结构体详见VmControlBaseInfo.h的GroupInputInfo
	 * @deprecated 弃用,推荐(SetParamsInfo(void * pParamData, const char * const strXmlPath)),绑定已导入的独立Group
     */
    inline qlonglong LoadIndependentGroup(qlonglong pSol);

    /**
     * @par 说明
     * 导入方案
	 * @param pSol [in] 方案信息结构体地址 结构体详见VmControlBaseInfo.h的SolutionInputInfo
     */
    inline qlonglong LoadSol(qlonglong pSol);
	
	/**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /**
     * @par 说明
     * 设置参数配置信息
	 * @param pData [in] 参数配置信息
     */
    inline void SetParamsInfo(qlonglong pData);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VMPARAMSCONTROLWINFORM_EXPORT VmParamsControlWinform : public QAxWidget
{
public:
    VmParamsControlWinform(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{10c9adfd-abb2-4ab3-bab4-26e568d12f1f}"));
    }

//    VmParamsControlWinform(IComponent *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmParamsControlWinform(IDisposable *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmParamsControlWinform(IWin32Window *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

    VmParamsControlWinform(VmParamsInterface *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Site
    */
    inline System::ISite* Site() const; //Returns the value of Site
    inline void SetSite(System::ISite* value); //Sets the value of the Site property

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Method Dispose
    */
    inline void Dispose();

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /**
     * @par 说明
     * 初始化
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /**
     * @par 说明
     * 导入独立Group
	 * @param pSol [in] Group信息结构体地址 结构体详见VmControlBaseInfo.h的GroupInputInfo
	 * @deprecated 弃用,推荐(SetParamsInfo(void * pParamData, const char * const strXmlPath)),绑定已导入的独立Group
     */
    inline qlonglong LoadIndependentGroup(qlonglong pSol);

    /**
     * @par 说明
     * 导入方案
	 * @param pSol [in] 方案信息结构体地址 结构体详见VmControlBaseInfo.h的SolutionInputInfo
     */
    inline qlonglong LoadSol(qlonglong pSol);

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /**
     * @par 说明
     * 设置参数配置信息
	 * @param pData [in] 参数配置信息
     */
    inline void SetParamsInfo(qlonglong pData);

    /*
    Method add_Disposed
    */
    inline void add_Disposed(mscorlib::_EventHandler* value);

    /*
    Method remove_Disposed
    */
    inline void remove_Disposed(mscorlib::_EventHandler* value);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VMPARAMSCONTROLWINFORM_NOINLINES
inline int VmParamsControlWinform::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline System::ISite* VmParamsControlWinform::Site() const
{
#ifdef QAX_DUMPCPP_SYSTEM_H
    System::ISite* qax_pointer = 0;
    qRegisterMetaType<System::ISite*>("System::ISite*", &qax_pointer);
    qRegisterMetaType<System::ISite>("System::ISite", qax_pointer);
    QVariant qax_result = property("Site");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(System::ISite**)qax_result.constData();
#else
    return 0; // foreign namespace not included
#endif
}
inline void VmParamsControlWinform::SetSite(System::ISite* value){
    int typeId = qRegisterMetaType<System::ISite*>("System::ISite*", &value);
    setProperty("Site", QVariant(typeId, &value));
}

inline QString VmParamsControlWinform::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline void VmParamsControlWinform::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline bool VmParamsControlWinform::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
    return qax_result;
}

inline int VmParamsControlWinform::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline qlonglong VmParamsControlWinform::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline mscorlib::_Type* VmParamsControlWinform::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline qlonglong VmParamsControlWinform::LoadIndependentGroup(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline qlonglong VmParamsControlWinform::LoadSol(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline void VmParamsControlWinform::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void VmParamsControlWinform::SetParamsInfo(qlonglong pData)
{
    void *_a[] = {0, (void*)&pData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VmParamsControlWinform::add_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void VmParamsControlWinform::remove_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}


inline void VmParamsInterface::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline qlonglong VmParamsInterface::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline qlonglong VmParamsInterface::LoadIndependentGroup(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline qlonglong VmParamsInterface::LoadSol(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void VmParamsInterface::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void VmParamsInterface::SetParamsInfo(qlonglong pData)
{
    void *_a[] = {0, (void*)&pData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VmParamsControlWinform::VmParamsControlWinform, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmParamsControlWinform::VmParamsControlWinform*>(t)->VmParamsControlWinform::~VmParamsControlWinform();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmParamsControlWinform::VmParamsControlWinform;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmParamsControlWinform::VmParamsControlWinform*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmParamsControlWinform::VmParamsControlWinform*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VmParamsControlWinform::VmParamsInterface, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmParamsControlWinform::VmParamsInterface*>(t)->VmParamsControlWinform::VmParamsInterface::~VmParamsInterface();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmParamsControlWinform::VmParamsInterface;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmParamsControlWinform::VmParamsInterface*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmParamsControlWinform::VmParamsInterface*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

