/****************************************************************************
**
** Metadata for VmParamsRenderControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {d45f15af-107e-48f6-9aa9-973c047e11a1}

****************************************************************************/

#define QAX_DUMPCPP_VMPARAMSRENDERCONTROLWINFORM_NOINLINES
#include "vmparamsrendercontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[87];
    char stringdata0[1126];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 58, 0),
QT_MOC_LITERAL(1, 59, 11, 0),
QT_MOC_LITERAL(2, 71, 10, 0),
QT_MOC_LITERAL(3, 82, 11, 0),
QT_MOC_LITERAL(4, 94, 11, 0),
QT_MOC_LITERAL(5, 106, 11, 0),
QT_MOC_LITERAL(6, 118, 12, 0),
QT_MOC_LITERAL(7, 131, 11, 0),
QT_MOC_LITERAL(8, 143, 23, 0),
QT_MOC_LITERAL(9, 167, 9, 0),
QT_MOC_LITERAL(10, 177, 0, 0),
QT_MOC_LITERAL(11, 178, 4, 0),
QT_MOC_LITERAL(12, 183, 6, 0),
QT_MOC_LITERAL(13, 190, 4, 0),
QT_MOC_LITERAL(14, 195, 4, 0),
QT_MOC_LITERAL(15, 200, 15, 0),
QT_MOC_LITERAL(16, 216, 4, 0),
QT_MOC_LITERAL(17, 221, 6, 0),
QT_MOC_LITERAL(18, 228, 4, 0),
QT_MOC_LITERAL(19, 233, 4, 0),
QT_MOC_LITERAL(20, 238, 29, 0),
QT_MOC_LITERAL(21, 268, 22, 0),
QT_MOC_LITERAL(22, 291, 16, 0),
QT_MOC_LITERAL(23, 308, 5, 0),
QT_MOC_LITERAL(24, 314, 7, 0),
QT_MOC_LITERAL(25, 322, 11, 0),
QT_MOC_LITERAL(26, 334, 6, 0),
QT_MOC_LITERAL(27, 341, 3, 0),
QT_MOC_LITERAL(28, 345, 11, 0),
QT_MOC_LITERAL(29, 357, 16, 0),
QT_MOC_LITERAL(30, 374, 27, 0),
QT_MOC_LITERAL(31, 402, 7, 0),
QT_MOC_LITERAL(32, 410, 16, 0),
QT_MOC_LITERAL(33, 427, 6, 0),
QT_MOC_LITERAL(34, 434, 18, 0),
QT_MOC_LITERAL(35, 453, 8, 0),
QT_MOC_LITERAL(36, 462, 20, 0),
QT_MOC_LITERAL(37, 483, 4, 0),
QT_MOC_LITERAL(38, 488, 7, 0),
QT_MOC_LITERAL(39, 496, 17, 0),
QT_MOC_LITERAL(40, 514, 8, 0),
QT_MOC_LITERAL(41, 523, 10, 0),
QT_MOC_LITERAL(42, 534, 17, 0),
QT_MOC_LITERAL(43, 552, 16, 0),
QT_MOC_LITERAL(44, 569, 14, 0),
QT_MOC_LITERAL(45, 584, 10, 0),
QT_MOC_LITERAL(46, 595, 13, 0),
QT_MOC_LITERAL(47, 609, 5, 0),
QT_MOC_LITERAL(48, 615, 9, 0),
QT_MOC_LITERAL(49, 625, 7, 0),
QT_MOC_LITERAL(50, 633, 10, 0),
QT_MOC_LITERAL(51, 644, 8, 0),
QT_MOC_LITERAL(52, 653, 18, 0),
QT_MOC_LITERAL(53, 672, 8, 0),
QT_MOC_LITERAL(54, 681, 7, 0),
QT_MOC_LITERAL(55, 689, 5, 0),
QT_MOC_LITERAL(56, 695, 26, 0),
QT_MOC_LITERAL(57, 722, 9, 0),
QT_MOC_LITERAL(58, 732, 19, 0),
QT_MOC_LITERAL(59, 752, 10, 0),
QT_MOC_LITERAL(60, 763, 13, 0),
QT_MOC_LITERAL(61, 777, 5, 0),
QT_MOC_LITERAL(62, 783, 11, 0),
QT_MOC_LITERAL(63, 795, 9, 0),
QT_MOC_LITERAL(64, 805, 10, 0),
QT_MOC_LITERAL(65, 816, 8, 0),
QT_MOC_LITERAL(66, 825, 11, 0),
QT_MOC_LITERAL(67, 837, 9, 0),
QT_MOC_LITERAL(68, 847, 12, 0),
QT_MOC_LITERAL(69, 860, 10, 0),
QT_MOC_LITERAL(70, 871, 18, 0),
QT_MOC_LITERAL(71, 890, 6, 0),
QT_MOC_LITERAL(72, 897, 17, 0),
QT_MOC_LITERAL(73, 915, 12, 0),
QT_MOC_LITERAL(74, 928, 7, 0),
QT_MOC_LITERAL(75, 936, 14, 0),
QT_MOC_LITERAL(76, 951, 4, 0),
QT_MOC_LITERAL(77, 956, 7, 0),
QT_MOC_LITERAL(78, 964, 5, 0),
QT_MOC_LITERAL(79, 970, 18, 0),
QT_MOC_LITERAL(80, 989, 10, 0),
QT_MOC_LITERAL(81, 1000, 12, 0),
QT_MOC_LITERAL(82, 1013, 24, 0),
QT_MOC_LITERAL(83, 1038, 15, 0),
QT_MOC_LITERAL(84, 1054, 8, 0),
QT_MOC_LITERAL(85, 1063, 53, 0),
QT_MOC_LITERAL(86, 1117, 7, 0)
    },
    "VmParamsRenderControlWinform::VmParamsRenderControlWinform\0Interface 1\0"
    "IComponent\0Interface 2\0IDisposable\0Interface 3\0IWin32Window\0Interface 4\0"
    "VmParamsRenderInterface\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0ChangeImageComboBoxVisibility\0isImageComboBoxVisible\0"
    "ClearDisplayView\0index\0Dispose\0EnlargeView\0Equals\0obj\0GetHashCode\0GetObjectPointer\0"
    "GetSelectedImageDisplayName\0GetType\0mscorlib::_Type*\0Handle\0HideCoordinateInfo\0"
    "InitView\0LoadIndependentGroup\0pSol\0LoadSol\0SaveOriginalImage\0fileName\0"
    "jpgQuality\0SaveRenderedImage\0SetAnnularSector\0pAnnularSector\0isAddShape\0"
    "SetBackground\0value\0SetCircle\0pCircle\0SetEllipse\0pEllipse\0SetImageSourceData\0"
    "pImgData\0SetLine\0pLine\0SetMultiImageButtonVisible\0isVisible\0SetParamTabEditable\0"
    "isEditable\0SetParamsInfo\0pData\0SetPointSet\0pPointSet\0SetPolygon\0pPolygon\0"
    "SetPolyline\0pPolyline\0SetRectangle\0pRectangle\0SetRenderCondition\0status\0"
    "SetRenderInterval\0pMillseconds\0SetSite\0System::ISite*\0Site\0SetText\0pText\0"
    "ShowCoordinateInfo\0ShrinkView\0add_Disposed\0mscorlib::_EventHandler*\0"
    "remove_Disposed\0ToString\0VmParamsRenderControlWinform::VmParamsRenderInterface\0"
    "control\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmParamsRenderControlWinform__VmParamsRenderControlWinform[] = {

 // content:
    7, // revision
    0,  // classname
    4, 14, // classinfo
    57, 22, // methods
    3, 490, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    1, 2, 
    3, 4, 
    5, 6, 
    7, 8, 

// signal: name, argc, parameters, tag, flags
    9, 4, 307, 10, 5,
    15, 1, 316, 10, 5,
    17, 3, 319, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 326, 10, 9,
    22, 0, 329, 10, 11,
    22, 1, 330, 10, 9,
    24, 0, 333, 10, 9,
    25, 0, 334, 10, 11,
    25, 1, 335, 10, 9,
    26, 1, 338, 10, 9,
    28, 0, 341, 10, 9,
    29, 0, 342, 10, 9,
    30, 0, 343, 10, 11,
    30, 1, 344, 10, 9,
    31, 0, 347, 10, 9,
    33, 0, 348, 10, 9,
    34, 0, 349, 10, 9,
    35, 0, 350, 10, 11,
    35, 1, 351, 10, 9,
    36, 1, 354, 10, 9,
    38, 1, 357, 10, 9,
    39, 1, 360, 10, 11,
    39, 2, 363, 10, 11,
    39, 3, 368, 10, 9,
    42, 1, 375, 10, 11,
    42, 2, 378, 10, 9,
    43, 1, 383, 10, 11,
    43, 2, 386, 10, 9,
    46, 1, 391, 10, 9,
    48, 1, 394, 10, 11,
    48, 2, 397, 10, 9,
    50, 1, 402, 10, 11,
    50, 2, 405, 10, 9,
    52, 1, 410, 10, 9,
    54, 1, 413, 10, 11,
    54, 2, 416, 10, 9,
    56, 1, 421, 10, 9,
    58, 1, 424, 10, 9,
    60, 1, 427, 10, 9,
    62, 1, 430, 10, 11,
    62, 2, 433, 10, 9,
    64, 1, 438, 10, 11,
    64, 2, 441, 10, 9,
    66, 1, 446, 10, 11,
    66, 2, 449, 10, 9,
    68, 1, 454, 10, 11,
    68, 2, 457, 10, 9,
    70, 1, 462, 10, 9,
    72, 1, 465, 10, 9,
    74, 1, 468, 10, 9,
    77, 1, 471, 10, 11,
    77, 2, 474, 10, 9,
    79, 0, 479, 10, 9,
    80, 0, 480, 10, 11,
    80, 1, 481, 10, 9,
    81, 1, 484, 10, 9,
    83, 1, 487, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 21,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Bool, QMetaType::QVariant, 27,
    QMetaType::Int,
    QMetaType::LongLong,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 23,
    0x80000000 | 32,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::LongLong, QMetaType::LongLong, 37,
    QMetaType::LongLong, QMetaType::LongLong, 37,
    QMetaType::Void, QMetaType::QString, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 40, 23,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::Int, 40, 23, 41,
    QMetaType::Void, QMetaType::QString, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 40, 41,
    QMetaType::Void, QMetaType::LongLong, 44,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 44, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::LongLong, 49,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 49, 45,
    QMetaType::Void, QMetaType::LongLong, 51,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 51, 45,
    QMetaType::Void, QMetaType::LongLong, 53,
    QMetaType::Void, QMetaType::LongLong, 55,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 55, 45,
    QMetaType::Void, QMetaType::Bool, 57,
    QMetaType::Void, QMetaType::Bool, 59,
    QMetaType::Void, QMetaType::LongLong, 61,
    QMetaType::Void, QMetaType::LongLong, 63,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 63, 45,
    QMetaType::Void, QMetaType::LongLong, 65,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 65, 45,
    QMetaType::Void, QMetaType::LongLong, 67,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 67, 45,
    QMetaType::Void, QMetaType::LongLong, 69,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 69, 45,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, 0x80000000 | 75, 76,
    QMetaType::Void, QMetaType::LongLong, 78,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 78, 45,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, 0x80000000 | 82, 47,
    QMetaType::Void, 0x80000000 | 82, 47,

 // properties: name, type, flags
    33, QMetaType::Int, 0x02005001, 		 // int Handle
    76, 0x80000000 | 75, 0x00015003, 		 // System::ISite* Site
    84, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmParamsRenderControlWinform::VmParamsRenderControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmParamsRenderControlWinform__VmParamsRenderControlWinform, 0, 0, 0 }
};

void *VmParamsRenderControlWinform::VmParamsRenderControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmParamsRenderControlWinform::VmParamsRenderControlWinform"))
        return static_cast<void*>(const_cast<VmParamsRenderControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_VmParamsRenderControlWinform__VmParamsRenderInterface[] = {

 // content:
    7, // revision
    85,  // classname
    0, 0, // classinfo
    50, 14, // methods
    1, 432, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    9, 4, 264, 10, 5,
    15, 1, 273, 10, 5,
    17, 3, 276, 10, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 283, 10, 9,
    22, 0, 286, 10, 11,
    22, 1, 287, 10, 9,
    24, 0, 290, 10, 9,
    25, 0, 291, 10, 11,
    25, 1, 292, 10, 9,
    29, 0, 295, 10, 9,
    30, 0, 296, 10, 11,
    30, 1, 297, 10, 9,
    34, 0, 300, 10, 9,
    35, 0, 301, 10, 11,
    35, 1, 302, 10, 9,
    36, 1, 305, 10, 9,
    38, 1, 308, 10, 9,
    39, 1, 311, 10, 11,
    39, 2, 314, 10, 11,
    39, 3, 319, 10, 9,
    42, 1, 326, 10, 11,
    42, 2, 329, 10, 9,
    43, 1, 334, 10, 11,
    43, 2, 337, 10, 9,
    46, 1, 342, 10, 9,
    48, 1, 345, 10, 11,
    48, 2, 348, 10, 9,
    50, 1, 353, 10, 11,
    50, 2, 356, 10, 9,
    52, 1, 361, 10, 9,
    54, 1, 364, 10, 11,
    54, 2, 367, 10, 9,
    56, 1, 372, 10, 9,
    58, 1, 375, 10, 9,
    60, 1, 378, 10, 9,
    62, 1, 381, 10, 11,
    62, 2, 384, 10, 9,
    64, 1, 389, 10, 11,
    64, 2, 392, 10, 9,
    66, 1, 397, 10, 11,
    66, 2, 400, 10, 9,
    68, 1, 405, 10, 11,
    68, 2, 408, 10, 9,
    70, 1, 413, 10, 9,
    72, 1, 416, 10, 9,
    77, 1, 419, 10, 11,
    77, 2, 422, 10, 9,
    79, 0, 427, 10, 9,
    80, 0, 428, 10, 11,
    80, 1, 429, 10, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 11, 12, 13, 14,
    QMetaType::Void, QMetaType::QString, 16,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 16, 18, 19,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 21,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::LongLong,
    QMetaType::QString,
    QMetaType::QString, QMetaType::Int, 23,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::LongLong, QMetaType::LongLong, 37,
    QMetaType::LongLong, QMetaType::LongLong, 37,
    QMetaType::Void, QMetaType::QString, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 40, 23,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::Int, 40, 23, 41,
    QMetaType::Void, QMetaType::QString, 40,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, 40, 41,
    QMetaType::Void, QMetaType::LongLong, 44,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 44, 45,
    QMetaType::Void, QMetaType::QString, 47,
    QMetaType::Void, QMetaType::LongLong, 49,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 49, 45,
    QMetaType::Void, QMetaType::LongLong, 51,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 51, 45,
    QMetaType::Void, QMetaType::LongLong, 53,
    QMetaType::Void, QMetaType::LongLong, 55,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 55, 45,
    QMetaType::Void, QMetaType::Bool, 57,
    QMetaType::Void, QMetaType::Bool, 59,
    QMetaType::Void, QMetaType::LongLong, 61,
    QMetaType::Void, QMetaType::LongLong, 63,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 63, 45,
    QMetaType::Void, QMetaType::LongLong, 65,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 65, 45,
    QMetaType::Void, QMetaType::LongLong, 67,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 67, 45,
    QMetaType::Void, QMetaType::LongLong, 69,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 69, 45,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Void, QMetaType::Int, 73,
    QMetaType::Void, QMetaType::LongLong, 78,
    QMetaType::Void, QMetaType::LongLong, QMetaType::Bool, 78, 45,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,

 // properties: name, type, flags
    86, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmParamsRenderControlWinform::VmParamsRenderInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmParamsRenderControlWinform__VmParamsRenderInterface, 0, 0, 0 }
};

void *VmParamsRenderControlWinform::VmParamsRenderInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmParamsRenderControlWinform::VmParamsRenderInterface"))
        return static_cast<void*>(const_cast<VmParamsRenderInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}

