/****************************************************************************
**
** Namespace VmProcedureControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {ff1facb1-b3cf-45b6-9c65-283a5823b4eb}

****************************************************************************/

#ifndef QAX_DUMPCPP_VMPROCEDURECONTROLWINFORM_H
#define QAX_DUMPCPP_VMPROCEDURECONTROLWINFORM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VMPROCEDURECONTROLWINFORM_EXPORT
#define VMPROCEDURECONTROLWINFORM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace System {
    class ISite;
}

namespace mscorlib {
    class _Type;
    class _EventHandler;
}

Q_DECLARE_OPAQUE_POINTER(System::ISite*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_Type*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_EventHandler*)

namespace VmProcedureControlWinform {


class VMPROCEDURECONTROLWINFORM_EXPORT VmProcedureControlInterface : public QAxObject
{
public:
    VmProcedureControlInterface(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method BindMultiProcedure
    */
    inline void BindMultiProcedure();

    /*
    Method BindSingleProcedure
    */
    inline void BindSingleProcedure(const QString& name);

    /**
     * @brief 释放控件资源
	 * @remarks 控件销毁前调用一次
     */
    inline void Dispose();

    /*
    Method GetObjectPointer
    */
    inline qlonglong GetObjectPointer();

    /*
    Method LockWorkArea
    */
    inline void LockWorkArea();

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method UnlockWorkArea
    */
    inline void UnlockWorkArea();

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VMPROCEDURECONTROLWINFORM_EXPORT VmProcedureControlWinform : public QAxWidget
{
public:
    VmProcedureControlWinform(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{4919fa4c-f224-4c1e-917c-89b7f37aae90}"));
    }

//    VmProcedureControlWinform(IComponent *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmProcedureControlWinform(IDisposable *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmProcedureControlWinform(IWin32Window *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

    VmProcedureControlWinform(VmProcedureControlInterface *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Site
    */
    inline System::ISite* Site() const; //Returns the value of Site
    inline void SetSite(System::ISite* value); //Sets the value of the Site property

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Method BindMultiProcedure
    */
    inline void BindMultiProcedure();

    /*
    Method BindSingleProcedure
    */
    inline void BindSingleProcedure(const QString& name);

    /*
    Method Dispose
    */
    inline void Dispose();

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /**
     * @par 说明
     * 初始化
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

    /*
    Method LockWorkArea
    */
    inline void LockWorkArea();

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method UnlockWorkArea
    */
    inline void UnlockWorkArea();

    /*
    Method add_Disposed
    */
    inline void add_Disposed(mscorlib::_EventHandler* value);

    /*
    Method remove_Disposed
    */
    inline void remove_Disposed(mscorlib::_EventHandler* value);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VMPROCEDURECONTROLWINFORM_NOINLINES
inline void VmProcedureControlInterface::BindMultiProcedure()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void VmProcedureControlInterface::BindSingleProcedure(const QString& name)
{
    void *_a[] = {0, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void VmProcedureControlInterface::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline qlonglong VmProcedureControlInterface::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void VmProcedureControlInterface::LockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void VmProcedureControlInterface::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void VmProcedureControlInterface::UnlockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}


inline int VmProcedureControlWinform::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline System::ISite* VmProcedureControlWinform::Site() const
{
#ifdef QAX_DUMPCPP_SYSTEM_H
    System::ISite* qax_pointer = 0;
    qRegisterMetaType<System::ISite*>("System::ISite*", &qax_pointer);
    qRegisterMetaType<System::ISite>("System::ISite", qax_pointer);
    QVariant qax_result = property("Site");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(System::ISite**)qax_result.constData();
#else
    return 0; // foreign namespace not included
#endif
}
inline void VmProcedureControlWinform::SetSite(System::ISite* value){
    int typeId = qRegisterMetaType<System::ISite*>("System::ISite*", &value);
    setProperty("Site", QVariant(typeId, &value));
}

inline QString VmProcedureControlWinform::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline void VmProcedureControlWinform::BindMultiProcedure()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline void VmProcedureControlWinform::BindSingleProcedure(const QString& name)
{
    void *_a[] = {0, (void*)&name};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
}

inline void VmProcedureControlWinform::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
}

inline bool VmProcedureControlWinform::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline int VmProcedureControlWinform::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline qlonglong VmProcedureControlWinform::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline mscorlib::_Type* VmProcedureControlWinform::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
    return qax_result;
}

inline void VmProcedureControlWinform::LockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void VmProcedureControlWinform::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void VmProcedureControlWinform::UnlockWorkArea()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline void VmProcedureControlWinform::add_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
}

inline void VmProcedureControlWinform::remove_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VmProcedureControlWinform::VmProcedureControlInterface, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmProcedureControlWinform::VmProcedureControlInterface*>(t)->VmProcedureControlWinform::VmProcedureControlInterface::~VmProcedureControlInterface();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmProcedureControlWinform::VmProcedureControlInterface;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmProcedureControlWinform::VmProcedureControlInterface*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmProcedureControlWinform::VmProcedureControlInterface*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VmProcedureControlWinform::VmProcedureControlWinform, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmProcedureControlWinform::VmProcedureControlWinform*>(t)->VmProcedureControlWinform::~VmProcedureControlWinform();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmProcedureControlWinform::VmProcedureControlWinform;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmProcedureControlWinform::VmProcedureControlWinform*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmProcedureControlWinform::VmProcedureControlWinform*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

