/****************************************************************************
**
** Namespace VmSingleModuleSetControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {042be3d0-fbe1-4ea6-b236-67731030e098}

****************************************************************************/

#ifndef QAX_DUMPCPP_VMSINGLEMODULESETCONTROLWINFORM_H
#define QAX_DUMPCPP_VMSINGLEMODULESETCONTROLWINFORM_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef VMSINGLEMODULESETCONTROLWINFORM_EXPORT
#define VMSINGLEMODULESETCONTROLWINFORM_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace
namespace System {
    class ISite;
}

namespace mscorlib {
    class _Type;
    class _EventHandler;
}

Q_DECLARE_OPAQUE_POINTER(System::ISite*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_Type*)
Q_DECLARE_OPAQUE_POINTER(mscorlib::_EventHandler*)

namespace VmSingleModuleSetControlWinform {


class VMSINGLEMODULESETCONTROLWINFORM_EXPORT VmSingleModuleSetControlInterface : public QAxObject
{
public:
    VmSingleModuleSetControlInterface(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /**
     * @brief 销毁独立Group
	 * @remarks 与LoadIndependentGroup(qlonglong pSol)配对使用
     */
    inline void DestroyIndependentGroup();

    /**
     * @brief 释放控件资源
	 * @remarks 控件销毁前调用一次
     */
    inline void Dispose();

     /**
     * @par 说明
     * 初始化
	 * @return 内部信息
     */
    inline qlonglong GetObjectPointer();

     /**
     * @brief 导入独立Group
	 * @param pSol [in] Group信息结构体地址 结构体详见VmControlBaseInfo.h的GroupInputInfo
	 * @remarks 与DestroyIndependentGroup()配对使用
     */
    inline qlonglong LoadIndependentGroup(qlonglong pSol);

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class VMSINGLEMODULESETCONTROLWINFORM_EXPORT VmSingleModuleSetControlWinform : public QAxWidget
{
public:
    VmSingleModuleSetControlWinform(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{0611e76e-3e97-42c7-8d2d-a8a42e928a7a}"));
    }

//    VmSingleModuleSetControlWinform(IComponent *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmSingleModuleSetControlWinform(IDisposable *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

//    VmSingleModuleSetControlWinform(IWin32Window *iface)
//    : QAxWidget()
//    {
//        initializeFrom(iface);
//        delete iface;
//    }

    VmSingleModuleSetControlWinform(VmSingleModuleSetControlInterface *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property Handle
    */
    inline int Handle() const; //Returns the value of Handle

    /*
    Property Site
    */
    inline System::ISite* Site() const; //Returns the value of Site
    inline void SetSite(System::ISite* value); //Sets the value of the Site property

    /*
    Property ToString
    */
    inline QString ToString() const; //Returns the value of ToString

    /*
    Method DestroyIndependentGroup
    */
    inline void DestroyIndependentGroup();

    /*
    Method Dispose
    */
    inline void Dispose();

    /*
    Method Equals
    */
    inline bool Equals(const QVariant& obj);

    /*
    Method GetHashCode
    */
    inline int GetHashCode();

    /*
    Method GetObjectPointer
    */
    inline qlonglong GetObjectPointer();

    /*
    Method GetType
    */
    inline mscorlib::_Type* GetType();

   /**
     * @par 说明
     * 导入独立Group
	 * @param pSol [in] Group信息结构体地址 结构体详见VmControlBaseInfo.h的GroupInputInfo
     */
    inline qlonglong LoadIndependentGroup(qlonglong pSol);

    /**
	 * @par 说明
	 * 流程、Group参数页中的添加、删除、编辑按钮是否可见
	 * @param isEditable [in] 是否可见   true 按钮可见
	*/
    inline void SetParamTabEditable(bool isEditable);

    /*
    Method add_Disposed
    */
    inline void add_Disposed(mscorlib::_EventHandler* value);

    /*
    Method remove_Disposed
    */
    inline void remove_Disposed(mscorlib::_EventHandler* value);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_VMSINGLEMODULESETCONTROLWINFORM_NOINLINES
inline void VmSingleModuleSetControlInterface::DestroyIndependentGroup()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void VmSingleModuleSetControlInterface::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline qlonglong VmSingleModuleSetControlInterface::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline qlonglong VmSingleModuleSetControlInterface::LoadIndependentGroup(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void VmSingleModuleSetControlInterface::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}


inline int VmSingleModuleSetControlWinform::Handle() const
{
    QVariant qax_result = property("Handle");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline System::ISite* VmSingleModuleSetControlWinform::Site() const
{
#ifdef QAX_DUMPCPP_SYSTEM_H
    System::ISite* qax_pointer = 0;
    qRegisterMetaType<System::ISite*>("System::ISite*", &qax_pointer);
    qRegisterMetaType<System::ISite>("System::ISite", qax_pointer);
    QVariant qax_result = property("Site");
    if (!qax_result.constData()) return 0;
    Q_ASSERT(qax_result.isValid());
    return *(System::ISite**)qax_result.constData();
#else
    return 0; // foreign namespace not included
#endif
}
inline void VmSingleModuleSetControlWinform::SetSite(System::ISite* value){
    int typeId = qRegisterMetaType<System::ISite*>("System::ISite*", &value);
    setProperty("Site", QVariant(typeId, &value));
}

inline QString VmSingleModuleSetControlWinform::ToString() const
{
    QVariant qax_result = property("ToString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline void VmSingleModuleSetControlWinform::DestroyIndependentGroup()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 35, _a);
}

inline void VmSingleModuleSetControlWinform::Dispose()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 36, _a);
}

inline bool VmSingleModuleSetControlWinform::Equals(const QVariant& obj)
{
    bool qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&obj};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
    return qax_result;
}

inline int VmSingleModuleSetControlWinform::GetHashCode()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
    return qax_result;
}

inline qlonglong VmSingleModuleSetControlWinform::GetObjectPointer()
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
    return qax_result;
}

inline mscorlib::_Type* VmSingleModuleSetControlWinform::GetType()
{
    mscorlib::_Type* qax_result = 0;
#ifdef QAX_DUMPCPP_MSCORLIB_H
    qRegisterMetaType<mscorlib::_Type*>("mscorlib::_Type*", &qax_result);
    qRegisterMetaType<mscorlib::_Type>("mscorlib::_Type", qax_result);
#endif
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
    return qax_result;
}

inline qlonglong VmSingleModuleSetControlWinform::LoadIndependentGroup(qlonglong pSol)
{
    qlonglong qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&pSol};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline void VmSingleModuleSetControlWinform::SetParamTabEditable(bool isEditable)
{
    void *_a[] = {0, (void*)&isEditable};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void VmSingleModuleSetControlWinform::add_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
}

inline void VmSingleModuleSetControlWinform::remove_Disposed(mscorlib::_EventHandler* value)
{
    void *_a[] = {0, (void*)&value};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface*>(t)->VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface::~VmSingleModuleSetControlInterface();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform*>(t)->VmSingleModuleSetControlWinform::~VmSingleModuleSetControlWinform();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

