/****************************************************************************
**
** Metadata for VmSingleModuleSetControlWinform generated by dumpcpp v5.9.9 using
** dumpcpp {042be3d0-fbe1-4ea6-b236-67731030e098}

****************************************************************************/

#define QAX_DUMPCPP_VMSINGLEMODULESETCONTROLWINFORM_NOINLINES
#include "vmsinglemodulesetcontrolwinform.h"

struct qt_meta_stringdata_all_t {
    QByteArrayData data[43];
    char stringdata0[588];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 66, 0),
QT_MOC_LITERAL(1, 67, 9, 0),
QT_MOC_LITERAL(2, 77, 0, 0),
QT_MOC_LITERAL(3, 78, 4, 0),
QT_MOC_LITERAL(4, 83, 6, 0),
QT_MOC_LITERAL(5, 90, 4, 0),
QT_MOC_LITERAL(6, 95, 4, 0),
QT_MOC_LITERAL(7, 100, 15, 0),
QT_MOC_LITERAL(8, 116, 4, 0),
QT_MOC_LITERAL(9, 121, 6, 0),
QT_MOC_LITERAL(10, 128, 4, 0),
QT_MOC_LITERAL(11, 133, 4, 0),
QT_MOC_LITERAL(12, 138, 23, 0),
QT_MOC_LITERAL(13, 162, 7, 0),
QT_MOC_LITERAL(14, 170, 16, 0),
QT_MOC_LITERAL(15, 187, 20, 0),
QT_MOC_LITERAL(16, 208, 4, 0),
QT_MOC_LITERAL(17, 213, 19, 0),
QT_MOC_LITERAL(18, 233, 10, 0),
QT_MOC_LITERAL(19, 244, 7, 0),
QT_MOC_LITERAL(20, 252, 64, 0),
QT_MOC_LITERAL(21, 317, 11, 0),
QT_MOC_LITERAL(22, 329, 10, 0),
QT_MOC_LITERAL(23, 340, 11, 0),
QT_MOC_LITERAL(24, 352, 11, 0),
QT_MOC_LITERAL(25, 364, 11, 0),
QT_MOC_LITERAL(26, 376, 12, 0),
QT_MOC_LITERAL(27, 389, 11, 0),
QT_MOC_LITERAL(28, 401, 33, 0),
QT_MOC_LITERAL(29, 435, 6, 0),
QT_MOC_LITERAL(30, 442, 3, 0),
QT_MOC_LITERAL(31, 446, 11, 0),
QT_MOC_LITERAL(32, 458, 7, 0),
QT_MOC_LITERAL(33, 466, 16, 0),
QT_MOC_LITERAL(34, 483, 6, 0),
QT_MOC_LITERAL(35, 490, 7, 0),
QT_MOC_LITERAL(36, 498, 14, 0),
QT_MOC_LITERAL(37, 513, 4, 0),
QT_MOC_LITERAL(38, 518, 12, 0),
QT_MOC_LITERAL(39, 531, 24, 0),
QT_MOC_LITERAL(40, 556, 5, 0),
QT_MOC_LITERAL(41, 562, 15, 0),
QT_MOC_LITERAL(42, 578, 8, 0)
    },
    "VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface\0exception\0"
    "\0code\0source\0disc\0help\0propertyChanged\0name\0signal\0argc\0argv\0DestroyIndependentGroup\0"
    "Dispose\0GetObjectPointer\0LoadIndependentGroup\0pSol\0SetParamTabEditable\0"
    "isEditable\0control\0VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform\0"
    "Interface 1\0IComponent\0Interface 2\0IDisposable\0Interface 3\0IWin32Window\0"
    "Interface 4\0VmSingleModuleSetControlInterface\0Equals\0obj\0GetHashCode\0GetType\0"
    "mscorlib::_Type*\0Handle\0SetSite\0System::ISite*\0Site\0add_Disposed\0"
    "mscorlib::_EventHandler*\0value\0remove_Disposed\0ToString\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VmSingleModuleSetControlWinform__VmSingleModuleSetControlInterface[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    8, 14, // methods
    1, 82, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 54, 2, 5,
    7, 1, 63, 2, 5,
    9, 3, 66, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 73, 2, 9,
    13, 0, 74, 2, 9,
    14, 0, 75, 2, 9,
    15, 1, 76, 2, 9,
    17, 1, 79, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::LongLong,
    QMetaType::LongLong, QMetaType::LongLong, 16,
    QMetaType::Void, QMetaType::Bool, 18,

 // properties: name, type, flags
    19, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmSingleModuleSetControlWinform__VmSingleModuleSetControlInterface, 0, 0, 0 }
};

void *VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmSingleModuleSetControlWinform::VmSingleModuleSetControlInterface"))
        return static_cast<void*>(const_cast<VmSingleModuleSetControlInterface*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_VmSingleModuleSetControlWinform__VmSingleModuleSetControlWinform[] = {

 // content:
    7, // revision
    20,  // classname
    4, 14, // classinfo
    15, 22, // methods
    3, 140, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    21, 22, 
    23, 24, 
    25, 26, 
    27, 28, 

// signal: name, argc, parameters, tag, flags
    1, 4, 97, 2, 5,
    7, 1, 106, 2, 5,
    9, 3, 109, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 116, 2, 9,
    13, 0, 117, 2, 9,
    29, 1, 118, 2, 9,
    31, 0, 121, 2, 9,
    14, 0, 122, 2, 9,
    32, 0, 123, 2, 9,
    34, 0, 124, 2, 9,
    15, 1, 125, 2, 9,
    17, 1, 128, 2, 9,
    35, 1, 131, 2, 9,
    38, 1, 134, 2, 9,
    41, 1, 137, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Bool, QMetaType::QVariant, 30,
    QMetaType::Int,
    QMetaType::LongLong,
    0x80000000 | 33,
    QMetaType::Int,
    QMetaType::LongLong, QMetaType::LongLong, 16,
    QMetaType::Void, QMetaType::Bool, 18,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, 0x80000000 | 39, 40,
    QMetaType::Void, 0x80000000 | 39, 40,

 // properties: name, type, flags
    34, QMetaType::Int, 0x02005001, 		 // int Handle
    37, 0x80000000 | 36, 0x00015003, 		 // System::ISite* Site
    42, QMetaType::QString, 0x0a005001, 		 // QString ToString

    0 // eod
};

const QMetaObject VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_VmSingleModuleSetControlWinform__VmSingleModuleSetControlWinform, 0, 0, 0 }
};

void *VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "VmSingleModuleSetControlWinform::VmSingleModuleSetControlWinform"))
        return static_cast<void*>(const_cast<VmSingleModuleSetControlWinform*>(this));
    return QAxWidget::qt_metacast(_clname);
}

